version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: magrit-redis
    command: redis-server /home/redis.conf
    volumes:
      - ./redis:/home
    networks:
       - app-network
    sysctls:
        net.core.somaxconn: 511

  nginx:
    container_name: magrit-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - magritapp
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - staticfiles:/var/www/static
    depends_on:
      - magritapp

  magritapp:
    container_name: magrit-app
    build:
      context: ../..
      dockerfile: misc/Docker/app/Dockerfile
    links:
      - redis
    networks:
      - app-network
    volumes:
      - staticfiles:/home/app/magrit/magrit_app/static
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  staticfiles:
